# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nmolina <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/11/09 19:44:02 by nmolina           #+#    #+#              #
#    Updated: 2017/11/09 21:18:27 by nmolina          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

all: 
	@gcc -o $(NAME) -Wall -Wextra -Werror $(NAME).c

clean:
	@/bin/rm -f *.o

fclean: clean
	@/bin/rm -f $(NAME)
